name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: mkdir -p /tmp/source{1..3} /tmp/dest1
      - run: ./shell/create_backup/scripts/temp.sh /tmp/source{1..3}


